// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjkg7YIdfINRTRH1Qq9_5EpPAdOYvawJM',
    appId: '1:213572755108:web:d07a6759c9049d31a01031',
    messagingSenderId: '213572755108',
    projectId: 'watercups-7c84f',
    authDomain: 'watercups-7c84f.firebaseapp.com',
    storageBucket: 'watercups-7c84f.appspot.com',
    measurementId: 'G-D1BKS0WJWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5kSfna4scn4XActS1dLT9YDP5Vq-iD6k',
    appId: '1:213572755108:android:06756f15f701404da01031',
    messagingSenderId: '213572755108',
    projectId: 'watercups-7c84f',
    storageBucket: 'watercups-7c84f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBykvKR_RYzuVnzEvttaVU3QWsm7Cci7kQ',
    appId: '1:213572755108:ios:94e45a6a02f51d41a01031',
    messagingSenderId: '213572755108',
    projectId: 'watercups-7c84f',
    storageBucket: 'watercups-7c84f.appspot.com',
    iosClientId: '213572755108-s4cg2m4bdbgduee7dsuouo5p00gsneno.apps.googleusercontent.com',
    iosBundleId: 'com.example.watercups',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBykvKR_RYzuVnzEvttaVU3QWsm7Cci7kQ',
    appId: '1:213572755108:ios:b25b9a466638d4a2a01031',
    messagingSenderId: '213572755108',
    projectId: 'watercups-7c84f',
    storageBucket: 'watercups-7c84f.appspot.com',
    iosClientId: '213572755108-agbd72pq4jrnddknt4p3t6u5mjakmuv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.watercups.RunnerTests',
  );
}
